### PR TITLE
implement a parse_schema function

### PR DESCRIPTION
**Pull request by scottbelden**
Not done with this yet, but pretty happy with the results so far. The high level take away is the following:

* `acquaint_schema` is no more
* `parse_schema` has been added
* It's not necessary to call `parse_schema` beforehand, but doing so will make future operations with that parsed schema faster

This PR will replace https://github.com/fastavro/fastavro/pull/214

### CODE REVIEW

**Comment by scottbelden** [comment]
Here is the benchmark results for the current master:

```
Small - 1 rec - 100,000 runs
Writing 1 records to one file...
... 100000 runs averaged 1.9614403247833253e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 2.2079241275787354e-05 seconds
Writing schemaless 1 records to one file...
... 100000 runs averaged 3.6337757110595705e-06 seconds
Reading schemaless 1 records from one file...
... 100000 runs averaged 2.4802041053771973e-06 seconds
Validating 1 records from one file...
... 100000 runs averaged 2.278144359588623e-06 seconds

Small - 100 rec - 1,000 runs
Writing 100 records to one file...
... 1000 runs averaged 9.727668762207031e-05 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.00013751840591430664 seconds
Writing schemaless 100 records to one file...
... 1000 runs averaged 0.00035809946060180666 seconds
Reading schemaless 100 records from one file...
... 1000 runs averaged 0.00023558521270751953 seconds
Validating 100 records from one file...
... 1000 runs averaged 0.0001869068145751953 seconds

Small - 10,000 rec - 10 runs
Writing 10000 records to one file...
... 10 runs averaged 0.007665681838989258 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.01274571418762207 seconds
Writing schemaless 10000 records to one file...
... 10 runs averaged 0.03574240207672119 seconds
Reading schemaless 10000 records from one file...
... 10 runs averaged 0.024326467514038087 seconds
Validating 10000 records from one file...
... 10 runs averaged 0.01814241409301758 seconds

Big - 1 rec - 100,000 runs
Writing 1 records to one file...
... 100000 runs averaged 3.592756986618042e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 3.61742377281189e-05 seconds
Writing schemaless 1 records to one file...
... 100000 runs averaged 9.809460639953612e-06 seconds
Reading schemaless 1 records from one file...
... 100000 runs averaged 8.361456394195557e-06 seconds
Validating 1 records from one file...
... 100000 runs averaged 8.26923131942749e-06 seconds

Big - 100 rec - 1,000 runs
Writing 100 records to one file...
... 1000 runs averaged 0.0004330573081970215 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.0006217644214630127 seconds
Writing schemaless 100 records to one file...
... 1000 runs averaged 0.0009919309616088867 seconds
Reading schemaless 100 records from one file...
... 1000 runs averaged 0.0008302147388458251 seconds
Validating 100 records from one file...
... 1000 runs averaged 0.0007796287536621094 seconds

Big - 10,000 rec - 10 runs
Writing 10000 records to one file...
... 10 runs averaged 0.039579916000366214 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.06534953117370605 seconds
Writing schemaless 10000 records to one file...
... 10 runs averaged 0.09927937984466553 seconds
Reading schemaless 10000 records from one file...
... 10 runs averaged 0.08218257427215576 seconds
Validating 10000 records from one file...
... 10 runs averaged 0.07849218845367431 seconds

Timestamp - 100,000 rec - 10 runs
Writing 100000 records to one file...
... 10 runs averaged 0.2568253755569458 seconds
Reading 100000 records from one file...
... 10 runs averaged 0.4534451007843018 seconds
Writing schemaless 100000 records to one file...
... 10 runs averaged 0.5900685310363769 seconds
Reading schemaless 100000 records from one file...
... 10 runs averaged 0.6430675029754639 seconds
Validating 100000 records from one file...
... 10 runs averaged 0.33096301555633545 seconds
```

And here they are for this branch when parsing beforehand:

```
Small - 1 rec - 100,000 runs
Writing 1 records to one file...
... 100000 runs averaged 1.4788806438446045e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 1.7746658325195314e-05 seconds
Writing schemaless 1 records to one file...
... 100000 runs averaged 1.2681961059570313e-06 seconds
Reading schemaless 1 records from one file...
... 100000 runs averaged 1.2066292762756348e-06 seconds
Validating 1 records from one file...
... 100000 runs averaged 2.0220947265625e-06 seconds

Small - 100 rec - 1,000 runs
Writing 100 records to one file...
... 1000 runs averaged 0.0001032412052154541 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.00012924909591674805 seconds
Writing schemaless 100 records to one file...
... 1000 runs averaged 0.0001243584156036377 seconds
Reading schemaless 100 records from one file...
... 1000 runs averaged 0.00011389517784118653 seconds
Validating 100 records from one file...
... 1000 runs averaged 0.00016098618507385254 seconds

Small - 10,000 rec - 10 runs
Writing 10000 records to one file...
... 10 runs averaged 0.00822741985321045 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.012413597106933594 seconds
Writing schemaless 10000 records to one file...
... 10 runs averaged 0.012491822242736816 seconds
Reading schemaless 10000 records from one file...
... 10 runs averaged 0.011623573303222657 seconds
Validating 10000 records from one file...
... 10 runs averaged 0.01598191261291504 seconds

Big - 1 rec - 100,000 runs
Writing 1 records to one file...
... 100000 runs averaged 2.787022113800049e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 2.887160301208496e-05 seconds
Writing schemaless 1 records to one file...
... 100000 runs averaged 4.638476371765136e-06 seconds
Reading schemaless 1 records from one file...
... 100000 runs averaged 5.006871223449707e-06 seconds
Validating 1 records from one file...
... 100000 runs averaged 7.793965339660645e-06 seconds

Big - 100 rec - 1,000 runs
Writing 100 records to one file...
... 1000 runs averaged 0.0004254436492919922 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.0005602345466613769 seconds
Writing schemaless 100 records to one file...
... 1000 runs averaged 0.0004633333683013916 seconds
Reading schemaless 100 records from one file...
... 1000 runs averaged 0.000500739574432373 seconds
Validating 100 records from one file...
... 1000 runs averaged 0.0007302398681640625 seconds

Big - 10,000 rec - 10 runs
Writing 10000 records to one file...
... 10 runs averaged 0.04056439399719238 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.05934724807739258 seconds
Writing schemaless 10000 records to one file...
... 10 runs averaged 0.046633362770080566 seconds
Reading schemaless 10000 records from one file...
... 10 runs averaged 0.04964067935943604 seconds
Validating 10000 records from one file...
... 10 runs averaged 0.07392323017120361 seconds

Timestamp - 100,000 rec - 10 runs
Writing 100000 records to one file...
... 10 runs averaged 0.25032892227172854 seconds
Reading 100000 records from one file...
... 10 runs averaged 0.4607595205307007 seconds
Writing schemaless 100000 records to one file...
... 10 runs averaged 0.3246826887130737 seconds
Reading schemaless 100000 records from one file...
... 10 runs averaged 0.4783992052078247 seconds
Validating 100000 records from one file...
... 10 runs averaged 0.2968855619430542 seconds
```

**Comment by scottbelden** [comment]
@vecchp Would you be able/interested in testing this out? The general idea is that you can call `fastavro.parse_schema` and pass that parsed schema into the `reader`/`writer` functions to prevent the schema needing to be parsed every time. I can push a pre-release to pypi if that would make it easier.

**Comment by vecchp** [comment]
@scottbelden Yes I would be able to. A pre release would be appreciated.

**Comment by scottbelden** [comment]
@vecchp I uploaded it as `0.21.0rc1`. Thanks for helping out.

**Comment by rhaarm** [comment]
@scottbelden great results on the increase in speed, I think we need to write a better output that can be consumed into Pandas and graphed out. I did a quick ipynb and adding all the data in manually from your log output, was definitely easier to identify with graphs and pandas. Either a json list or a list of tuples with this following format is awesome.

```
columns = ['message_size', 'records', 'runs', 'func', 'run_time']
for action, run_time in [('write', 0.2568253755569458),
                         ('read', 0.4534451007843018),
                         ('write_schemaless', 0.5900685310363769),
                         ('read_schemaless', 0.6430675029754639), 
                         ('validate', 0.33096301555633545)]:
    data.append(('timestamp', '100000', '10', action, run_time))
```
**Main Run Times**
image

**Parser changes Run Times**
image

**Percent Difference**
image

**Comment by scottbelden** [comment]
@rhaarm Thanks for the output. The text output from the benchmark script isn't the best so I'm definitely open to modifying it into a format that is more digestible.

**Comment by vecchp** [comment]
@scottbelden do you still need me to test this now that we have the benchmarks?

**Comment by scottbelden** [comment]
@vecchp If you'd like to. The information gained from you or someone else testing would be if there were any issues with the `parse_schema` function, not necessarily the speed. However, the function at the moment is pretty simple and the current test suite caught some issues along the way, so I'm pretty confident that it's fine.

I'll probably merge and release this at some point today.

**Pull request merged**
