### PR TITLE
(work-in-progress, do not merge): Compile schemas into executable code

### PR DESCRIPTION
**Pull request by spenczar**
We talked about this in #505.

I have made some good progress, which I'd like to share. I generate a Python AST for a given schema, which means I don't need to use `eval` which is nice. It compiles into a function which can then read data from a file-like source and spits out the deserialized data.

In early microbenchmarks, this is performing very well. Benchmark-running code is in `tests/benchmark_compilation.py`; the benchmark test cases are in `tests/test_ast_compilation.py`. Full results are [in a gist](https://gist.github.com/spenczar/ee835e213ddd3a04ddcd80639e463aa6), but in summary:
 - Reading records and unions is ~3-4x faster
 - Reading maps and arrays are ~1.2x faster
 - Reading enums, fixed types, logical types, and schemas which are just a primitive is ~2x faster

Of course, this is balanced by the compilation time, which can be a few milliseconds even for a simple schema. It nice to provide a way to cache compilation (in case they're reading a lot of files, all of which have the same schema, for example).

By hacking around with the `linecache` package, I'm able to get generated source code to appear in tracebacks, which is nice. Still, the generated code can be pretty strange.

This sort of code generation is not easy to read, and might be so hard to maintain that you don't want to pursue this - I'd understand. I have become very very familiar with the `ast` package by this point, but it's weird stuff. I am also not so sure how well Python versions will maintain compatibility going forward.

TODOs
--------------
- [x] Compile reader for a given schema
- [ ] Compile writer for a given schema
- [x] Handle recursive schemas
- [ ] Handle schema evolution
   - [ ] Skip fields which are removed in reader schema
   - [ ] Set defaults for fields which are added in reader schema
   - [ ] Handle type promotion
   - [ ] Handle field reordering
 - [x] Remove dependencies on Python 3.9
 - [ ] Use in existing fastavro tests

### CODE REVIEW

**Comment by spenczar** [comment]
An example of generated code, if you use `ast.unparse` to decompile the AST into source code (`ast.parse` as added in Python 3.9): https://gist.github.com/spenczar/dcf2828958e13edcd6a2c53091bc4c0b

**Comment by scottbelden** [comment]
This is really interesting and the initial benchmarks do look nice. I've worked with `ast` in the past so I'm at least a little familiar with the concept and format.I'll try to find some time to take a deeper look at this and give some more detailed thoughts.

[I also played around with an approach similar to the `spavro`](https://github.com/fastavro/fastavro/pull/507) idea of pre-parsing the schema and generating a writer function that only depends on the data, but I haven't figured out if it is actually beneficial.

**Comment by scottbelden** [comment]
@spenczar Hey, I wanted to take an initial stab at trying to replicate some of the results you've gotten, but I think I might be doing something wrong...

I found the schema you mentioned in your gist, but I didn't have any data to work with, so I tried generating some arbitrary data. Then I tried to set up a script similar to `test_ast_compiler_read_file` in `tests/test_ast_compile.py`. Here's a gist with the schema you provided, the test records I generated, and the script I used to do the timing: https://gist.github.com/scottbelden/9501ad51cb4892a2ab32789d3777a613

At the end I got these timings:

```
Write time: 0.45223498344421387
Read time: 0.19674086570739746
Compile Read time: 0.17552995681762695
```

I see that the compiled read time is indeed faster. Does this performance change match what you have been seeing and what you mentioned in the original post, or am I doing something wrong? Thanks!

**Comment by spenczar** [comment]
Nice, thanks for the concise speed test. Yes, I get similar results:
```
-> % python3.9 test_speed.py             
Write time: 0.3856966495513916
Read time: 0.17666053771972656
Compile Read time: 0.1411588191986084
```

So about 20% faster.

The dramatic benchmarks (like "70% faster") come from micro benchmarks, which you can run with `python tests/benchmark_compilation.py` in this branch. Those might not be meaningful.

I was seeing better results when working a bit with real data - more like 30%. I'll try to get some of that real data into a gist so we can run your script against it - one sec.

**Comment by spenczar** [comment]
Okay, raw data here: https://github.com/spenczar/astro_data_share/blob/main/astro_records.avro. Couldn't do a gist because it's too big, and couldn't do JSON because it's too big, sorry.

It's 1000 records created with `fastavro.writer`. It's pretty much the same performance (relatively) that you saw in your synthetic test:

```
1000
Write time: 0.9514408111572266
Read time: 0.36310553550720215
Compile Read time: 0.2846710681915283
```
This is a 21% improvement in runtime.
---
So - is this worth all the complexity of this change? I'm not totally convinced, myself. The microbenchmarks, like of very simple records, were way more convincing.

**Comment by spenczar** [comment]
I have spun this off into a separate project, https://github.com/spenczar/avroc. Thanks for thinking it through with me and exploring the design - I really appreciate it.

**Pull request closed without merging**
